
services:
  bigtop-hostname0:
    hostname: bigtop-hostname0.demo.local
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    ports:
      - "8080:8080"
      #- "3000:3000"
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      ambari_net:
        ipv4_address: 172.28.0.100

  bigtop-hostname1:
    hostname: bigtop-hostname1.demo.local
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      ambari_net:
        ipv4_address: 172.28.0.101

  bigtop-hostname2:
    hostname: bigtop-hostname2.demo.local
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      ambari_net:
        ipv4_address: 172.28.0.102

  bigtop-hostname3:
    hostname: bigtop-hostname3.demo.local
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./ambari-repo:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      ambari_net:
        ipv4_address: 172.28.0.103

networks:
  ambari_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
